apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-cicd-app
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production-cicd-app
  template:
    metadata:
      labels:
        app: production-cicd-app
    spec:
      containers:
        - name: production-cicd-app
          image: swaroopp03/production-cicd-app:fd9054779248ccae000ae09e5e05a647c7290fc4
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
