namespace: production

replicaCount: 2

image:
  repository: swaroopp03/production-cicd-app
  tag: 213b11fd748c81c036ecb7de1441cf7f12e9ba9b
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
