namespace: production

replicaCount: 2

image:
  repository: swaroopp03/production-cicd-app
  tag: 550c5ab7133f86899f1a399402084d384b467456
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
